import { Annotation } from '@langchain/langgraph';
import type {
  GatekeeperOutput,
  ResearchFinding,
  CriticOutput,
  SynthesizerOutput,
} from '../schemas';

/**
 * LangGraph State Definition for the Recursive Research Agent System.
 * Adheres strictly to typed JSON object payloads for all agent handoffs.
 */
export const ResearchStateAnnotation = Annotation.Root({
  /**
   * The original user query / prompt
   */
  originalQuery: Annotation<string>({
    reducer: (_, next) => next,
    default: () => '',
  }),

  /**
   * Gatekeeper evaluation output (triage decision, reasoning, optional direct response)
   */
  gatekeeper: Annotation<GatekeeperOutput | undefined>({
    reducer: (_, next) => next,
    default: () => undefined,
  }),

  /**
   * Current list of active sub-questions to research in this iteration.
   * Reducer: Overwrites with the latest sub-queries generated by Planner or Critic.
   */
  subQueries: Annotation<string[]>({
    reducer: (_, next) => next,
    default: () => [],
  }),

  /**
   * Aggregated research findings across parallel researcher runs and recursive cycles.
   * Reducer: Appends new findings to existing findings array.
   */
  researchData: Annotation<ResearchFinding[]>({
    reducer: (prev, next) => (Array.isArray(next) ? prev.concat(next) : prev),
    default: () => [],
  }),

  /**
   * Current recursion depth counter (enforces MAX_DEPTH budget).
   * Reducer: Overwrites with the latest depth count.
   */
  depth: Annotation<number>({
    reducer: (_, next) => next,
    default: () => 0,
  }),

  /**
   * Critic evaluation output (isSatisfied, critique, missingAspects, nextSubQueries).
   */
  critic: Annotation<CriticOutput | undefined>({
    reducer: (_, next) => next,
    default: () => undefined,
  }),

  /**
   * Fast access flag indicating if the critic is satisfied with research data.
   * Reducer: Overwrites with latest verdict.
   */
  isSatisfied: Annotation<boolean>({
    reducer: (_, next) => next,
    default: () => false,
  }),

  /**
   * Structured synthesized final report output.
   */
  synthesis: Annotation<SynthesizerOutput | undefined>({
    reducer: (_, next) => next,
    default: () => undefined,
  }),

  /**
   * Final markdown output string ready for user presentation (either direct answer or full report).
   * Reducer: Overwrites with final presentation string.
   */
  finalReport: Annotation<string>({
    reducer: (_, next) => next,
    default: () => '',
  }),
});

/**
 * Inferred TypeScript state types
 */
export type ResearchState = typeof ResearchStateAnnotation.State;
export type ResearchStateUpdate = typeof ResearchStateAnnotation.Update;
