import { searchTavily } from '../services';
import type {
  ResearchFinding,
  ResearchState,
  ResearchStateUpdate,
} from '../state';

/**
 * Executes search retrieval for a single sub-query.
 *
 * @param query - The targeted sub-query string
 * @param maxResults - Optional max results per sub-query (default: 3)
 * @returns Array of structured ResearchFinding objects
 */
export async function executeSingleResearch(
  query: string,
  maxResults: number = 3
): Promise<ResearchFinding[]> {
  const trimmed = query.trim();
  if (!trimmed) return [];

  return searchTavily(trimmed, maxResults);
}

/**
 * Orchestrates concurrent execution of Researcher nodes across multiple sub-queries.
 * Uses Promise.allSettled to guarantee that a failure in one query does not abort the entire batch.
 *
 * @param subQueries - Array of sub-queries generated by Planner or Critic
 * @param maxResultsPerQuery - Optional max results per sub-query (default: 3)
 * @returns Aggregated array of ResearchFinding objects
 */
export async function executeParallelResearch(
  subQueries: string[],
  maxResultsPerQuery: number = 3
): Promise<ResearchFinding[]> {
  if (!subQueries || subQueries.length === 0) {
    console.warn('[Researcher] No sub-queries provided for research.');
    return [];
  }

  console.log(
    `[Researcher] Spawning ${subQueries.length} parallel research worker(s)...`
  );

  const searchPromises = subQueries.map(async (query, index) => {
    console.log(`  [Worker ${index + 1}] Searching: "${query}"`);
    const findings = await executeSingleResearch(query, maxResultsPerQuery);
    console.log(
      `  [Worker ${index + 1}] Completed. Retrieved ${findings.length} source(s).`
    );
    return findings;
  });

  const settledResults = await Promise.allSettled(searchPromises);

  const aggregatedFindings: ResearchFinding[] = [];

  for (let i = 0; i < settledResults.length; i++) {
    const result = settledResults[i];
    if (result.status === 'fulfilled') {
      aggregatedFindings.push(...result.value);
    } else {
      console.error(
        `  [Worker ${i + 1}] Failed for query "${subQueries[i]}":`,
        result.reason
      );
    }
  }

  console.log(
    `[Researcher] Parallel research complete. Total findings gathered in this round: ${aggregatedFindings.length}`
  );

  return aggregatedFindings;
}

/**
 * LangGraph node handler for the Researcher agent.
 *
 * @param state - Current research state containing subQueries to search
 * @returns State updates containing researchData (which appends via reducer)
 */
export async function researcherNode(
  state: ResearchState
): Promise<ResearchStateUpdate> {
  const { subQueries, depth } = state;

  console.log(
    `\n[Researcher Node] Starting research execution for Depth Round ${depth}`
  );

  const newFindings = await executeParallelResearch(subQueries);

  return {
    researchData: newFindings,
  };
}
