import pLimit from 'p-limit';
import { searchTavily } from '../services';
import { env } from '../config';
import type {
  ResearchFinding,
  ResearchState,
  ResearchStateUpdate,
} from '../state';

/**
 * Executes search retrieval for a single sub-query.
 *
 * @param query - The targeted sub-query string
 * @param maxResults - Optional max results per sub-query (default: 3)
 * @returns Array of structured ResearchFinding objects
 */
export async function executeSingleResearch(
  query: string,
  maxResults: number = 3
): Promise<ResearchFinding[]> {
  const trimmed = query.trim();
  if (!trimmed) return [];

  return searchTavily(trimmed, maxResults);
}

/**
 * Orchestrates concurrent execution of Researcher nodes across multiple sub-queries.
 * Uses Promise.allSettled to guarantee that a failure in one query does not abort the entire batch.
 *
 * @param subQueries - Array of sub-queries generated by Planner or Critic
 * @param maxResultsPerQuery - Optional max results per sub-query (default: env.MAX_RESULTS_PER_QUERY)
 * @param existingUrls - Optional Set of already visited URLs to avoid duplicates
 * @returns Aggregated array of ResearchFinding objects
 */
export async function executeParallelResearch(
  subQueries: string[],
  maxResultsPerQuery: number = env.MAX_RESULTS_PER_QUERY,
  existingUrls: Set<string> = new Set()
): Promise<ResearchFinding[]> {
  if (!subQueries || subQueries.length === 0) {
    console.warn('[Researcher] No sub-queries provided for research.');
    return [];
  }

  console.log(
    `[Researcher] Spawning ${subQueries.length} parallel research worker(s)...`
  );

  const limit = pLimit(env.CONCURRENCY_LIMIT);

  const searchPromises = subQueries.map((query, index) => limit(async () => {
    console.log(`  [Worker ${index + 1}] Searching: "${query}"`);
    const findings = await executeSingleResearch(query, maxResultsPerQuery);
    console.log(
      `  [Worker ${index + 1}] Completed. Retrieved ${findings.length} source(s).`
    );
    return findings;
  }));

  const settledResults = await Promise.allSettled(searchPromises);

  const aggregatedFindings: ResearchFinding[] = [];
  const localSeenUrls = new Set<string>(existingUrls);

  for (let i = 0; i < settledResults.length; i++) {
    const result = settledResults[i];
    if (result.status === 'fulfilled') {
      for (const finding of result.value) {
        if (!finding.url || !localSeenUrls.has(finding.url)) {
          if (finding.url) localSeenUrls.add(finding.url);
          aggregatedFindings.push(finding);
        }
      }
    } else {
      console.error(
        `  [Worker ${i + 1}] Failed for query "${subQueries[i]}":`,
        result.reason
      );
    }
  }

  console.log(
    `[Researcher] Parallel research complete. Total findings gathered in this round: ${aggregatedFindings.length}`
  );

  return aggregatedFindings;
}

/**
 * LangGraph node handler for the Researcher agent.
 *
 * @param state - Current research state containing subQueries to search
 * @returns State updates containing researchData (which appends via reducer)
 */
export async function researcherNode(
  state: ResearchState
): Promise<ResearchStateUpdate> {
  const { subQueries, depth, researchData } = state;

  console.log(
    `\n[Researcher Node] Starting research execution for Depth Round ${depth}`
  );

  const existingUrls = new Set(researchData?.map(f => f.url).filter(Boolean) as string[]);

  const newFindings = await executeParallelResearch(
    subQueries,
    env.MAX_RESULTS_PER_QUERY,
    existingUrls
  );

  return {
    researchData: newFindings,
  };
}
