import pLimit from 'p-limit';
import { searchTavily } from '../services';
import { env } from '../config';
import { logger } from '../utils';
import type {
  ResearchFinding,
  ResearchState,
  ResearchStateUpdate,
} from '../state';

/**
 * Executes search retrieval for a single sub-query.
 *
 * @param query - The targeted sub-query string
 * @param maxResults - Optional max results per sub-query (default: 3)
 * @returns Array of structured ResearchFinding objects
 */
export async function executeSingleResearch(
  query: string,
  maxResults: number = 3
): Promise<ResearchFinding[]> {
  const trimmed = query.trim();
  if (!trimmed) return [];

  return searchTavily(trimmed, maxResults);
}

/**
 * Orchestrates concurrent execution of Researcher nodes across multiple sub-queries.
 * Uses Promise.allSettled to guarantee that a failure in one query does not abort the entire batch.
 *
 * @param subQueries - Array of sub-queries generated by Planner or Critic
 * @param maxResultsPerQuery - Optional max results per sub-query (default: env.MAX_RESULTS_PER_QUERY)
 * @param existingUrls - Optional Set of already visited URLs to avoid duplicates
 * @returns Aggregated array of ResearchFinding objects
 */
export async function executeParallelResearch(
  subQueries: string[],
  maxResultsPerQuery: number = env.MAX_RESULTS_PER_QUERY,
  existingUrls: Set<string> = new Set()
): Promise<ResearchFinding[]> {
  if (!subQueries || subQueries.length === 0) {
    logger.warn('No sub-queries provided for research.');
    return [];
  }

  const limit = pLimit(env.CONCURRENCY_LIMIT);

  const searchPromises = subQueries.map((query, index) => limit(async () => {
    logger.workerStart(index + 1, query);
    try {
      const findings = await executeSingleResearch(query, maxResultsPerQuery);
      logger.workerSuccess(index + 1, findings.length);
      return findings;
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      logger.workerError(index + 1, query, errMsg);
      return [];
    }
  }));

  const settledResults = await Promise.allSettled(searchPromises);

  const aggregatedFindings: ResearchFinding[] = [];
  const localSeenUrls = new Set<string>(existingUrls);

  for (let i = 0; i < settledResults.length; i++) {
    const result = settledResults[i];
    if (result.status === 'fulfilled') {
      for (const finding of result.value) {
        if (!finding.url || !localSeenUrls.has(finding.url)) {
          if (finding.url) localSeenUrls.add(finding.url);
          aggregatedFindings.push(finding);
        }
      }
    } else {
      logger.workerError(i + 1, subQueries[i], String(result.reason));
    }
  }

  return aggregatedFindings;
}

/**
 * LangGraph node handler for the Researcher agent.
 *
 * @param state - Current research state containing subQueries to search
 * @returns State updates containing researchData (which appends via reducer)
 */
export async function researcherNode(
  state: ResearchState
): Promise<ResearchStateUpdate> {
  const { subQueries, depth, researchData } = state;

  logger.researcherRoundStart(depth, env.MAX_DEPTH, subQueries.length);

  const existingUrls = new Set(researchData?.map(f => f.url).filter(Boolean) as string[]);

  const newFindings = await executeParallelResearch(
    subQueries,
    env.MAX_RESULTS_PER_QUERY,
    existingUrls
  );

  const updatedData = [...(researchData || []), ...newFindings];
  logger.researcherRoundComplete(newFindings.length, updatedData.length);

  return {
    researchData: updatedData,
  };
}

